name: Weather Notify

on:
  schedule:
    # 5:55 AM IST = 00:25 UTC
    - cron: "25 0 * * *"

  workflow_dispatch:

jobs:
  weather-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up server
        run: |
          echo "Waking Weather Notify server..."

          curl --fail --max-time 120 \
            https://weather-notify-tau.vercel.app/api/health

      - name: Wait for server
        run: |
          echo "Waiting 5 minutes for server to be fully ready..."
          sleep 300

      - name: Send weather alerts
        run: |
          echo "Sending weather alerts..."

          curl --fail --max-time 120 \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://weather-notify-tau.vercel.app/api/cron/weather-alert

      - name: Completed
        run: |
          echo "Weather alert workflow completed successfully."
